module.exports = {
  cond: require('./cond'),
  getGlobal: require('./global').getGlobal,
  setGlobal: require('./global').setGlobal,
  getAllGlobal: require('./global').getAllGlobal,
  deleteGlobal: require('./global').deleteGlobal,
  clearGlobal: require('./global').clearGlobal,
  exists: require('./exists'),
  isDefined: require('./isDefined'),
  isEither: require('./isEither'),
  run: require('./run'),
  swit: require('./swit'),
  toggle: require('./toggle'),
  wait: require('./wait'),
}
