export { default as ifs } from './ifs'
export { default as exists } from './exists'
export { getGlobal } from './global'
export { setGlobal } from './global'
export { getAllGlobal } from './global'
export { deleteGlobal } from './global'
export { clearGlobal } from './global'
export { default as isDefined } from './isDefined'
export { default as isEither } from './isEither'
export { default as run } from './run'
export { default as swit } from './swit'
export { default as toggle } from './toggle'
export { default as wait } from './wait'
